### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Xlt3h** [ExtraordinaryWisdom/Instagram-Login-Script#2]
Traceback (most recent call last):
  File "C:/Users/RECHEESe/AppData/Local/Programs/Python/Python37/instagram_brute_force.py", line 20, in <module>
    session.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
  File "C:\Users\RECHEESe\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\RECHEESe\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

**Comment by dedshit** [comment]
dont you know they changed so many things

**Comment by dedshit** [comment]
> Traceback (most recent call last):
> File "C:/Users/RECHEESe/AppData/Local/Programs/Python/Python37/instagram_brute_force.py", line 20, in
> session.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
> File "C:\Users\RECHEESe\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\cookies.py", line 328, in **getitem**
> return self._find_no_duplicates(name)
> File "C:\Users\RECHEESe\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
> raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
> KeyError: "name='csrftoken', domain=None, path=None"



you need to send necessary headers like content length , cookie, content-type etc and form

**Comment by Miniflint** [comment]
So what the code would look like ?

> 
> 
> > Traceback (most recent call last):
> > File "C:/Users/RECHEESe/AppData/Local/Programs/Python/Python37/instagram_brute_force.py", line 20, in
> > session.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
> > File "C:\Users\RECHEESe\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\cookies.py", line 328, in **getitem**
> > return self._find_no_duplicates(name)
> > File "C:\Users\RECHEESe\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
> > raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
> > KeyError: "name='csrftoken', domain=None, path=None"
> 
> you need to send necessary headers like content length , cookie, content-type etc and form

So what the code would look like ?

**Comment by dedshit** [comment]
@Miniflint i'm not freelancer to do this 

inspect xhr while login & do your stuff

**Comment by dedshit** [comment]
> So what the code would look like ?
> 
> > > Traceback (most recent call last):
> > > File "C:/Users/RECHEESe/AppData/Local/Programs/Python/Python37/instagram_brute_force.py", line 20, in
> > > session.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
> > > File "C:\Users\RECHEESe\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\cookies.py", line 328, in **getitem**
> > > return self._find_no_duplicates(name)
> > > File "C:\Users\RECHEESe\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
> > > raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
> > > KeyError: "name='csrftoken', domain=None, path=None"
> > 
> > 
> > you need to send necessary headers like content length , cookie, content-type etc and form
> 
> So what the code would look like ?



Check my pull request
